# For any modification consulte /usr/share/doc/alacritty/example/alacritty.yml for the example configuration 

window:
  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 10
    y: 10

# Background opacity
#
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
background_opacity: 0.6
# background_opacity: 0.80

# Fonts 
font:
  normal:
    family: Hack Nerd Font
    style: Regular

  bold:
    family: Hack Nerd Font
    style: Bold

  italic:
    family: Hack Nerd Font
    style: Italic

  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic

  size: 10

colors:
  # Default colors
  primary:
    background: '0x0f101a'
    foreground: '0xc5c9de'

  # Normal colors
  normal:
    black:   '0x181a29'
    red:     '0xF07178'
    green:   '0xcdea9f'
    yellow:  '0xffd47e'
    blue:    '0x93bbff'
    magenta: '0xd3a7ee'
    cyan:    '0x98e4ff'
    white:   '0xbfd5de'

  # Bright colors
  bright:
    black:   '0x282a40'
    red:     '0xeb7f84'
    green:   '0xe0ffad'
    yellow:  '0xffee7e'
    blue:    '0xa3c5ff'
    magenta: '0xd6afed'
    cyan:    '0x98fffd'
    white:   '0xd1e5ed' 
  
  
    
cursor:
  # Cursor style
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    shape: Beam
    # Cursor blinking state
    #
    # Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: On
  
  url:
    # URL launcher
    #
    # This program is executed when clicking on a text which is recognized as a URL.
    # The URL is always added to the command as the last parameter.
    launcher: explorer

    # URL modifiers
    #
    # These are the modifiers that need to be held down for opening URLs when clicking
    # on them. The available modifiers are documented in the key binding section.
    #modifiers: Control|Shift

# Use middle button for paste 
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

